name: "Track TODO Action"
description: "Sync TODO/BUG/FIXME comments with GitHub Issues"
author: "Taras Kushnir"
inputs:
  REPO:
    description: "Repository"
    default: ""
  TOKEN:
    description: "Github token"
    default: ""
  INCLUDE_PATTERN:
    description: "Regexp for source files to include"
    default: ""
  EXCLUDE_PATTERN:
    description: "Regexp for source files to exclude"
    default: ""
  ROOT:
    description: "Root directory for source code"
    default: "."
  MIN_WORDS:
    description: "Minimum amount of words to create an issue"
    default: "3"
  MIN_CHARACTERS:
    description: "Minimum amount of characters to create an issue"
    default: "30"
  DRY_RUN:
    description: "Do not create or close real issues"
    default: ""
  ADD_LIMIT:
    description: "Limit number of issues to create during workflow"
    default: ""
  CLOSE_LIMIT:
    description: "Limit number of issues to close during workflow"
    default: ""
  LABEL:
    description: "Label to add for new issues"
    default: "todo comment"
  SHA:
    description: "SHA value of the commit"
    default: ""
  REF:
    description: "Github Ref that triggered the workflow (branch or tag)"
    default: ""
  EXTENDED_LABELS:
    description: "Create additional labels to mark branch, issue type etc."
    default: "1"

outputs:

runs:
  using: "docker"
  image: "Dockerfile"

branding:
  icon: "check-square"
  color: "green"
