name: Build
on:
  push:
    branches:
    - '*'
    paths-ignore:
    - 'docs/**'
    - '**/README.md'
    tags-ignore:
    - '*.*'
  pull_request:
    types: [opened, reopened]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go 1.19
        uses: actions/setup-go@v5
        with:
          go-version: 1.19
        id: go

      - uses: actions/checkout@v4

      - name: Build
        env:
          GIT_COMMIT: "${{ github.sha }}"
        run: |
          make vendors
          make build
