name: Build and Release Go Project

on:
  push:
    tags:
      - 'v*.*.*' # Triggers the workflow on version tags (e.g., v1.0.0)

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.23

      - name: Set up environment
        run: |
          go env -w GOFLAGS="-mod=vendor"

      - name: Build the Go project
        run: |
          CGO_ENABLED=0 go build -ldflags="-w -s" -v -o app .

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        with:
          tag_name: ${{ github.ref_name }}
          release_name: Release ${{ github.ref_name }}
          draft: false
          prerelease: false
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./app
          asset_name: app
          asset_content_type: application/octet-stream
